# This is a basic workflow to help you get started with Actions

name: Java CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  java_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out code
        uses: actions/checkout@v2
      
      # Setup Java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
    
      # Check directory
      - name: Directory
        run: ls -la $GITHUB_WORKSPACE
      
      # Change permissions
      - name: Permissions
        run: chmod -R +x $GITHUB_WORKSPACE
        
      # Change directory, build and run programs
      - name: AddTwo
        run: |
          cd 1/HW
          ls -la
          sudo javac AddTwo.java
          sudo java AddTwo
          
      - name: Ex
        run: |
          cd 1/HW
          ls -la
          sudo javac Ex.java
          sudo java Ex
        
      - name: IfEx
        run: |
          sudo javac IfEx.java
          sudo java IfEx  
        
       # Change directory, build and run programs
      - name: Largest Div
        run: |
          cd $GITHUB_WORKSPACE/2/HW
          sudo javac LargestDiv.java
          sudo java LargestDiv
          
      - name: Loops
        run: |
          sudo javac Loops.java
          sudo java Loops
                 
      # Runs the Encrypt program
      - name: Encrypt
        run: |
          cd Encrypt_Decrypt
          sudo java Encrypt.java < sampleText r.r
        
      # Print Encrypt Results
      - name: Encrypt Results
        run: cat r.r

      # Print Decrypt program
      - name: Decrypt
        run: sudo java Decrypt.java < r.r decrypt.txt
        
      # Print Decrypt Results
      - name: Decrypt Results
        run: cat decrypt.txt
        
      # Change directory, build and run programs
      - name: Emp_Ex
        run: |
          cd $GITHUB_WORKSPACE/3.0/HW/Emp_Ex
          sudo javac Emp_Ex.java
          sudo java Emp_Ex
          
      - name: Emp_Ex4
        run: |
          cd $GITHUB_WORKSPACE/3.0/HW/Emp_Ex4
          sudo javac Emp_Ex4.java
          sudo java Emp_Ex4
          
      - name: Emp_Ex12
        run: |
          cd $GITHUB_WORKSPACE/3.0/HW/Emp_Ex12
          sudo javac Emp_Ex12.java
          sudo java Emp_Ex12
          
      - name: Extra_Credit
        run: |
          cd $GITHUB_WORKSPACE/3.0/HW/Extra_Credit
          sudo javac Customer_Ex.java
          sudo java Customer_Ex

